// blog-system/pages/about.vue
<script setup lang="ts">
import { Heart, Sparkles, Zap, Shield, Rocket } from 'lucide-vue-next'

useSeoMeta({
  title: '关于我们 | 元气银行博客',
  description: '了解元气银行博客的初衷、愿景和我们的团队。'
})
</script>

<template>
  <div class="min-h-screen bg-white">
    <header class="py-24 bg-gradient-to-br from-brand-pink/5 via-brand-purple/5 to-white border-b border-gray-50">
      <div class="container mx-auto px-4 text-center">
        <div class="w-20 h-20 bg-white rounded-3xl shadow-2xl flex items-center justify-center mx-auto mb-8 animate-bounce">
          <Logo class="w-10 h-10 text-brand-pink" />
        </div>
        <h1 class="text-4xl lg:text-7xl font-black text-gray-900 mb-6 tracking-tight">我们的故事</h1>
        <p class="text-xl text-gray-500 font-medium max-w-2xl mx-auto leading-relaxed">
          让教育回归有趣，让习惯自然养成。
        </p>
      </div>
    </header>

    <div class="container mx-auto px-4 py-24 max-w-4xl space-y-24">
      <section class="space-y-8">
        <h2 class="text-3xl font-black text-gray-900 flex items-center gap-4">
          <Sparkles class="w-8 h-8 text-brand-pink" />
          为什么是元气银行？
        </h2>
        <div class="prose prose-lg text-gray-600 font-medium leading-loose">
          <p>
            在忙碌的现代家庭生活中，教育往往变成了琐碎的叮嘱和重复的纠正。我们相信，最好的教育方式是激发孩子内在的驱动力。
          </p>
          <p>
            元气银行（Family Points Bank）的初衷，就是通过一套简单的“积分-愿望”系统，将枯燥的家务和习惯培养变成一项有趣的家庭游戏。
          </p>
        </div>
      </section>

      <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div v-for="val in [
          { title: '完全公益', icon: Heart, desc: '我们是一个非盈利性质的项目，所有功能对所有家庭完全免费。' },
          { title: '数据隐私', icon: Shield, desc: '您的家庭数据受到严格保护，我们永远不会买卖您的任何信息。' }
        ]" :key="val.title" class="p-10 rounded-[48px] bg-gray-50 border border-gray-100 space-y-4">
          <component :is="val.icon" class="w-10 h-10 text-brand-purple" />
          <h3 class="text-2xl font-black text-gray-900">{{ val.title }}</h3>
          <p class="text-gray-500 font-medium leading-relaxed">{{ val.desc }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

// blog-system/src/app/(frontend)/about/page.tsx
import { Zap, Target, Heart, Users, Sparkles } from 'lucide-react'
import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '关于我们',
  description: '了解元气银行的使命、愿景和核心价值观。我们致力于通过科技的力量，帮助每个家庭建立积极的激励机制，让孩子在快乐中成长。',
  openGraph: {
    title: '关于我们 | 元气银行博客',
    description: '了解元气银行的使命、愿景和核心价值观',
    type: 'website',
  },
}

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white">
      {/* Hero */}
      <div className="bg-gradient-to-br from-purple-50 via-pink-50 to-white border-b border-purple-100">
        <div className="container mx-auto px-6 py-20">
          <div className="max-w-6xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-white rounded-full text-sm font-bold text-purple-600 mb-6 shadow-sm border border-purple-100">
              <Sparkles className="w-4 h-4" />
              关于我们
            </div>
            <h1 className="text-5xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent leading-tight">
              让家庭激励变得<br />简单高效
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
              元气银行是一个专为家庭设计的积分管理系统，通过游戏化的方式激励家庭成员养成良好习惯
            </p>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-6 py-20">
        <div className="max-w-6xl mx-auto space-y-20">
          {/* Mission */}
          <div className="relative overflow-hidden bg-gradient-to-br from-purple-600 via-pink-600 to-purple-600 rounded-3xl p-12 md:p-16 text-white shadow-2xl">
            <div className="absolute top-0 right-0 w-96 h-96 bg-white/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"></div>
            <div className="absolute bottom-0 left-0 w-96 h-96 bg-white/10 rounded-full translate-y-1/2 -translate-x-1/2"></div>
            
            <div className="relative z-10 text-center max-w-3xl mx-auto">
              <h2 className="text-4xl font-bold mb-6">我们的使命</h2>
              <p className="text-xl text-white/90 leading-relaxed">
                通过科技的力量，帮助每个家庭建立积极的激励机制，让孩子在快乐中成长，让家庭关系更加和谐
              </p>
            </div>
          </div>

          {/* Values */}
          <div>
            <div className="text-center mb-12">
              <h2 className="text-4xl font-bold mb-4 bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">核心价值观</h2>
              <p className="text-gray-600 text-lg">指引我们前进的核心理念</p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="group bg-white rounded-2xl p-8 border border-gray-100 hover:border-purple-200 hover:shadow-2xl transition-all">
                <div className="w-14 h-14 bg-gradient-to-br from-purple-100 to-pink-100 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  <Target className="w-7 h-7 text-purple-600" />
                </div>
                <h3 className="text-2xl font-bold mb-3 text-gray-900">简单易用</h3>
                <p className="text-gray-600 leading-relaxed">
                  我们相信好的产品应该简单直观，让每个家庭成员都能轻松上手，无需复杂的学习过程
                </p>
              </div>

              <div className="group bg-white rounded-2xl p-8 border border-gray-100 hover:border-pink-200 hover:shadow-2xl transition-all">
                <div className="w-14 h-14 bg-gradient-to-br from-pink-100 to-rose-100 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  <Heart className="w-7 h-7 text-pink-600" />
                </div>
                <h3 className="text-2xl font-bold mb-3 text-gray-900">以人为本</h3>
                <p className="text-gray-600 leading-relaxed">
                  我们关注每个家庭的独特需求，提供灵活的配置选项，让系统真正服务于家庭
                </p>
              </div>

              <div className="group bg-white rounded-2xl p-8 border border-gray-100 hover:border-indigo-200 hover:shadow-2xl transition-all">
                <div className="w-14 h-14 bg-gradient-to-br from-indigo-100 to-purple-100 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  <Zap className="w-7 h-7 text-indigo-600" />
                </div>
                <h3 className="text-2xl font-bold mb-3 text-gray-900">持续创新</h3>
                <p className="text-gray-600 leading-relaxed">
                  我们不断探索新的技术和方法，为用户提供更好的体验和更强大的功能
                </p>
              </div>

              <div className="group bg-white rounded-2xl p-8 border border-gray-100 hover:border-fuchsia-200 hover:shadow-2xl transition-all">
                <div className="w-14 h-14 bg-gradient-to-br from-fuchsia-100 to-pink-100 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  <Users className="w-7 h-7 text-fuchsia-600" />
                </div>
                <h3 className="text-2xl font-bold mb-3 text-gray-900">用心服务</h3>
                <p className="text-gray-600 leading-relaxed">
                  我们倾听用户的声音，快速响应反馈，用心打磨每一个细节，让产品更贴近用户需求
                </p>
              </div>
            </div>
          </div>

          {/* Story */}
          <div className="bg-white rounded-3xl p-12 md:p-16 border border-gray-100 shadow-lg">
            <h2 className="text-4xl font-bold mb-8 bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">我们的故事</h2>
            <div className="space-y-6 text-gray-600 text-lg leading-relaxed">
              <p>
                元气银行诞生于一个普通家庭的需求。作为父母，我们希望通过积极的方式激励孩子养成良好的生活习惯，
                但传统的奖励方式往往难以持续，也缺乏系统性的记录和管理。
              </p>
              <p>
                于是，我们决定开发一个简单易用的家庭积分管理系统。通过游戏化的设计，让孩子在完成任务、
                养成习惯的过程中获得成就感，同时也让家长能够更好地跟踪和管理激励机制。
              </p>
              <p>
                今天，元气银行已经帮助数百个家庭建立了积极的激励体系，我们将继续努力，
                为更多家庭带来便利和快乐。
              </p>
            </div>
          </div>

          {/* CTA */}
          <div className="relative overflow-hidden bg-gradient-to-br from-purple-600 via-pink-600 to-purple-600 rounded-3xl p-12 md:p-16 text-white shadow-2xl">
            <div className="absolute top-0 right-0 w-96 h-96 bg-white/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"></div>
            
            <div className="relative z-10 text-center">
              <h2 className="text-4xl font-bold mb-4">加入我们的社区</h2>
              <p className="text-xl text-white/90 mb-8 max-w-2xl mx-auto">
                开始使用元气银行，让家庭激励变得更加简单高效
              </p>
              <Link
                href="https://blog.familybank.chat"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-8 py-4 bg-white text-purple-600 rounded-xl font-bold text-lg hover:bg-purple-50 transition-all hover:scale-105 shadow-lg"
              >
                立即免费体验
                <Sparkles className="w-5 h-5" />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
