// blog-system-nextjs-backup/src/app/dashboard/page.tsx
import { createClient } from '@/lib/supabase/server'
import { FileText, Eye, MessageSquare, Users, Plus, ArrowRight, FolderOpen, Tag, AlertCircle, Clock } from 'lucide-react'
import Link from 'next/link'
import { formatDate, formatAuthorName } from '@/lib/utils'
import { QuickReviewActions } from '@/components/dashboard/QuickReviewActions'

export default async function DashboardPage() {
  const supabase = await createClient()
  
  const { data: { user } } = await supabase.auth.getUser()
  const { data: profile } = await supabase
    .from('profiles')
    .select('name, role, family_id')
    .eq('id', user?.id)
    .maybeSingle()

  // 检查是否是超管
  const isSuperAdmin = profile?.role === 'admin' && profile?.family_id === '79ed05a1-e0e5-4d8c-9a79-d8756c488171'

  // Get statistics - 根据权限过滤
  // 构建统计查询
  let postsCountQuery = supabase.from('posts').select('*', { count: 'exact', head: true })
  let commentsCountQuery = supabase.from('comments').select('*', { count: 'exact', head: true })
  let viewsQuery = supabase.from('posts').select('view_count')
  
  // 如果不是超管，只统计自己的数据
  if (!isSuperAdmin) {
    postsCountQuery = postsCountQuery.eq('author_id', user?.id)
    viewsQuery = viewsQuery.eq('author_id', user?.id)
    
    // 评论：只统计自己文章的评论
    // 需要通过 posts 表关联
    commentsCountQuery = supabase
      .from('comments')
      .select('*, posts!inner(author_id)', { count: 'exact', head: true })
      .eq('posts.author_id', user?.id)
  }
  
  const [
    { count: totalPosts },
    { count: totalComments },
    { data: totalViews }
  ] = await Promise.all([
    postsCountQuery,
    commentsCountQuery,
    viewsQuery
  ])

  // 用户数统计：只有超管才显示
  let totalUsers = 0
  if (isSuperAdmin) {
    const { count } = await supabase.from('profiles').select('*', { count: 'exact', head: true })
    totalUsers = count || 0
  }

  const viewCount = totalViews?.reduce((sum, post) => sum + (post.view_count || 0), 0) || 0 || 0

  // Get recent posts with author info
  // 非超管只能看到自己的文章
  let recentPostsQuery = supabase
    .from('posts')
    .select(`
      id, 
      title, 
      status, 
      review_status,
      updated_at, 
      view_count,
      profiles!posts_author_id_fkey(name, avatar_url)
    `)
    .order('updated_at', { ascending: false })
    .limit(5)
  
  // 如果不是超管，只显示自己的文章
  if (!isSuperAdmin) {
    recentPostsQuery = recentPostsQuery.eq('author_id', user?.id)
  }
  
  const { data: recentPosts } = await recentPostsQuery

  // Get pending posts (only for super admin)
  let pendingPosts = null
  if (isSuperAdmin) {
    const { data } = await supabase
      .from('posts')
      .select(`
        id, 
        title, 
        status,
        review_status,
        created_at,
        profiles!posts_author_id_fkey(name, avatar_url)
      `)
      .eq('review_status', 'pending')
      .order('created_at', { ascending: false })
      .limit(5)
    pendingPosts = data
  }

  // Get pending comments (only for super admin)
  let pendingComments = null
  if (isSuperAdmin) {
    const { data } = await supabase
      .from('comments')
      .select(`
        id,
        content,
        author_name,
        created_at,
        post_id,
        posts!inner(title, slug)
      `)
      .eq('status', 'pending')
      .order('created_at', { ascending: false })
      .limit(5)
    pendingComments = data
  }

  const stats = {
    totalPosts: totalPosts || 0,
    totalViews: viewCount,
    totalComments: totalComments || 0,
    totalUsers: totalUsers || 0,
  }

  return (
    <div className="space-y-6 sm:space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-black bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] bg-clip-text text-transparent mb-2 tracking-tight">
            欢迎回来，{profile?.name || user?.email?.split('@')[0] || '用户'}
          </h1>
          <p className="text-sm sm:text-base text-gray-600 font-medium">查看数据统计和最新动态</p>
        </div>
        <Link
          href="/dashboard/posts/new"
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-5 sm:px-6 py-2.5 sm:py-3 bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] text-white rounded-2xl font-black hover:shadow-xl hover:scale-105 active:scale-95 transition-all text-sm sm:text-base"
        >
          <Plus className="w-4 h-4 sm:w-5 sm:h-5" />
          <span>新建文章</span>
        </Link>
      </div>

      {/* Stats Grid */}
      <div className={`grid grid-cols-1 sm:grid-cols-2 ${isSuperAdmin ? 'lg:grid-cols-4' : 'lg:grid-cols-3'} gap-4 sm:gap-6`}>
        <div className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all">
          <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
          <div className="relative">
            <div className="flex items-center justify-between mb-4">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                <FileText className="w-6 h-6 text-[#FF4D94]" />
              </div>
              <span className="text-xs font-black text-[#FF4D94] bg-[#FF4D94]/10 px-3 py-1 rounded-full uppercase tracking-wider">文章</span>
            </div>
            <div className="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{stats.totalPosts}</div>
            <div className="text-xs sm:text-sm text-gray-600 font-bold">{isSuperAdmin ? '总文章数' : '我的文章'}</div>
          </div>
        </div>

        <div className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#7C4DFF]/30 transition-all">
          <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
          <div className="relative">
            <div className="flex items-center justify-between mb-4">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                <Eye className="w-6 h-6 text-[#7C4DFF]" />
              </div>
              <span className="text-xs font-black text-[#7C4DFF] bg-[#7C4DFF]/10 px-3 py-1 rounded-full uppercase tracking-wider">浏览</span>
            </div>
            <div className="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{stats.totalViews.toLocaleString()}</div>
            <div className="text-xs sm:text-sm text-gray-600 font-bold">{isSuperAdmin ? '总浏览量' : '我的浏览量'}</div>
          </div>
        </div>

        <div className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all">
          <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
          <div className="relative">
            <div className="flex items-center justify-between mb-4">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                <MessageSquare className="w-6 h-6 text-[#FF4D94]" />
              </div>
              <span className="text-xs font-black text-[#FF4D94] bg-[#FF4D94]/10 px-3 py-1 rounded-full uppercase tracking-wider">评论</span>
            </div>
            <div className="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{stats.totalComments}</div>
            <div className="text-xs sm:text-sm text-gray-600 font-bold">{isSuperAdmin ? '总评论数' : '我的评论数'}</div>
          </div>
        </div>

        {/* 只有超管才显示用户统计 */}
        {isSuperAdmin && (
          <div className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#7C4DFF]/30 transition-all">
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
            <div className="relative">
              <div className="flex items-center justify-between mb-4">
                <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <Users className="w-6 h-6 text-[#7C4DFF]" />
                </div>
                <span className="text-xs font-black text-[#7C4DFF] bg-[#7C4DFF]/10 px-3 py-1 rounded-full uppercase tracking-wider">用户</span>
              </div>
              <div className="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{stats.totalUsers}</div>
              <div className="text-xs sm:text-sm text-gray-600 font-bold">注册用户</div>
            </div>
          </div>
        )}
      </div>

      {/* Recent Posts */}
      <div className="bg-white rounded-3xl border border-gray-100 shadow-lg overflow-hidden">
        <div className="p-5 sm:p-6 border-b border-gray-100 bg-gradient-to-r from-[#FF4D94]/5 to-[#7C4DFF]/5">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div>
              <h2 className="text-xl sm:text-2xl font-black text-gray-900 mb-1">最近文章</h2>
              <p className="text-xs sm:text-sm text-gray-600 font-medium">{isSuperAdmin ? '最近发布的内容' : '您最近发布的内容'}</p>
            </div>
            <Link
              href="/dashboard/posts"
              className="flex items-center gap-2 text-xs sm:text-sm font-black text-[#FF4D94] hover:text-[#7C4DFF] transition-colors"
            >
              查看全部
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
        <div className="divide-y divide-gray-100">
          {recentPosts && recentPosts.length > 0 ? (
            recentPosts.map((post: any) => (
              <div
                key={post.id}
                className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 sm:p-6 hover:bg-gradient-to-r hover:from-[#FF4D94]/5 hover:to-[#7C4DFF]/5 transition-all group"
              >
                <Link
                  href={`/dashboard/posts/${post.id}/edit`}
                  className="flex-1 min-w-0"
                >
                  <h3 className="font-black text-base sm:text-lg text-gray-900 mb-2 group-hover:text-[#FF4D94] transition-colors line-clamp-2">
                    {post.title}
                  </h3>
                  <div className="flex flex-wrap items-center gap-2 sm:gap-4 text-xs sm:text-sm text-gray-600">
                    <span className="font-black text-[#FF4D94]">
                      {formatAuthorName(post.profiles)}
                    </span>
                    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold ${
                      post.status === 'published' 
                        ? 'bg-green-50 text-green-700 border border-green-200' 
                        : 'bg-yellow-50 text-yellow-700 border border-yellow-200'
                    }`}>
                      <span className={`w-1.5 h-1.5 rounded-full ${
                        post.status === 'published' ? 'bg-green-500' : 'bg-yellow-500'
                      }`}></span>
                      {post.status === 'published' ? '已发布' : '草稿'}
                    </span>
                    {post.review_status && (
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold ${
                        post.review_status === 'approved' 
                          ? 'bg-blue-50 text-blue-700 border border-blue-200'
                          : post.review_status === 'pending'
                          ? 'bg-orange-50 text-orange-700 border border-orange-200'
                          : 'bg-red-50 text-red-700 border border-red-200'
                      }`}>
                        {post.review_status === 'approved' ? '已审核' : post.review_status === 'pending' ? '待审核' : '已拒绝'}
                      </span>
                    )}
                    <span className="flex items-center gap-1 font-medium">
                      <Eye className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                      {post.view_count} 浏览
                    </span>
                    <span className="font-medium">{formatDate(post.updated_at)}</span>
                  </div>
                </Link>
                <div className="flex items-center gap-2 flex-shrink-0">
                  {isSuperAdmin && post.review_status === 'pending' && (
                    <QuickReviewActions
                      type="post"
                      id={post.id}
                    />
                  )}
                  <Link href={`/dashboard/posts/${post.id}/edit`}>
                    <ArrowRight className="w-5 h-5 text-gray-400 group-hover:text-[#FF4D94] group-hover:translate-x-1 transition-all" />
                  </Link>
                </div>
              </div>
            ))
          ) : (
            <div className="p-12 text-center">
              <div className="w-16 h-16 rounded-3xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center mx-auto mb-4">
                <FileText className="w-8 h-8 text-[#FF4D94]" />
              </div>
              <p className="text-gray-600 font-bold">还没有文章，开始创作第一篇吧！</p>
            </div>
          )}
        </div>
      </div>

      {/* Pending Posts (Admin Only) */}
      {isSuperAdmin && pendingPosts && pendingPosts.length > 0 && (
        <div className="bg-white rounded-3xl border border-orange-100 shadow-lg overflow-hidden">
          <div className="p-5 sm:p-6 border-b border-orange-100 bg-gradient-to-r from-orange-50/50 to-yellow-50/50">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-orange-100 to-yellow-100 flex items-center justify-center">
                  <Clock className="w-5 h-5 text-orange-600" />
                </div>
                <div>
                  <h2 className="text-xl sm:text-2xl font-black text-gray-900 mb-1">待审核文章</h2>
                  <p className="text-xs sm:text-sm text-gray-600 font-medium">需要您审核的文章</p>
                </div>
              </div>
              <Link
                href="/dashboard/posts"
                className="flex items-center gap-2 text-xs sm:text-sm font-black text-orange-600 hover:text-orange-700 transition-colors"
              >
                查看全部
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>
          <div className="divide-y divide-gray-100">
            {pendingPosts.map((post: any) => (
              <div
                key={post.id}
                className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 sm:p-6 hover:bg-gradient-to-r hover:from-orange-50/30 hover:to-yellow-50/30 transition-all group"
              >
                <Link href={`/dashboard/posts/${post.id}/review`} className="flex-1 min-w-0">
                  <h3 className="font-black text-base sm:text-lg text-gray-900 mb-2 group-hover:text-orange-600 transition-colors line-clamp-2">
                    {post.title}
                  </h3>
                  <div className="flex flex-wrap items-center gap-2 sm:gap-4 text-xs sm:text-sm text-gray-600">
                    <span className="font-black text-[#FF4D94]">
                      {formatAuthorName(post.profiles)}
                    </span>
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold bg-orange-50 text-orange-700 border border-orange-200">
                      <AlertCircle className="w-3 h-3" />
                      待审核
                    </span>
                    <span className="font-medium">{formatDate(post.created_at)}</span>
                  </div>
                </Link>
                <div className="flex items-center gap-3 flex-shrink-0">
                  <QuickReviewActions type="post" id={post.id} />
                  <Link href={`/dashboard/posts/${post.id}/review`}>
                    <ArrowRight className="w-5 h-5 text-gray-400 group-hover:text-orange-600 transition-all" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Pending Comments (Admin Only) */}
      {isSuperAdmin && pendingComments && pendingComments.length > 0 && (
        <div className="bg-white rounded-3xl border border-blue-100 shadow-lg overflow-hidden">
          <div className="p-5 sm:p-6 border-b border-blue-100 bg-gradient-to-r from-blue-50/50 to-indigo-50/50">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-blue-100 to-indigo-100 flex items-center justify-center">
                  <MessageSquare className="w-5 h-5 text-blue-600" />
                </div>
                <div>
                  <h2 className="text-xl sm:text-2xl font-black text-gray-900 mb-1">待审核评论</h2>
                  <p className="text-xs sm:text-sm text-gray-600 font-medium">需要您审核的评论</p>
                </div>
              </div>
              <Link
                href="/dashboard/comments"
                className="flex items-center gap-2 text-xs sm:text-sm font-black text-blue-600 hover:text-blue-700 transition-colors"
              >
                查看全部
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>
          <div className="divide-y divide-gray-100">
            {pendingComments.map((comment: any) => (
              <div
                key={comment.id}
                className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 sm:p-6 hover:bg-gradient-to-r hover:from-blue-50/30 hover:to-indigo-50/30 transition-all group"
              >
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-2 sm:gap-3 mb-2">
                    <span className="font-black text-gray-900">{comment.author_name}</span>
                    <span className="text-xs sm:text-sm text-gray-500 font-medium">评论了</span>
                    <Link 
                      href={`/blog/${comment.posts?.slug}`}
                      className="text-xs sm:text-sm font-bold text-[#FF4D94] hover:text-[#7C4DFF] truncate max-w-xs transition-colors"
                    >
                      {comment.posts?.title}
                    </Link>
                  </div>
                  <p className="text-xs sm:text-sm text-gray-700 mb-2 line-clamp-2 font-medium">{comment.content}</p>
                  <div className="flex flex-wrap items-center gap-2 sm:gap-4 text-xs sm:text-sm text-gray-600">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold bg-blue-50 text-blue-700 border border-blue-200">
                      <AlertCircle className="w-3 h-3" />
                      待审核
                    </span>
                    <span className="font-medium">{formatDate(comment.created_at)}</span>
                  </div>
                </div>
                <div className="flex items-center gap-3 flex-shrink-0">
                  <QuickReviewActions type="comment" id={comment.id} />
                  <Link href="/dashboard/comments">
                    <ArrowRight className="w-5 h-5 text-gray-400 group-hover:text-blue-600 transition-all" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Quick Actions - 只有超管才显示 */}
      {isSuperAdmin && (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
          <Link
            href="/dashboard/categories"
            className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all"
          >
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
            <div className="relative">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                <FolderOpen className="w-6 h-6 text-[#FF4D94]" />
              </div>
              <h3 className="font-black text-lg text-gray-900 mb-2 group-hover:text-[#FF4D94] transition-colors">管理分类</h3>
              <p className="text-sm text-gray-600 mb-4 font-medium">组织和管理文章分类</p>
              <div className="flex items-center gap-2 text-sm font-black text-[#FF4D94]">
                <span>前往管理</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </div>
            </div>
          </Link>

          <Link
            href="/dashboard/tags"
            className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#7C4DFF]/30 transition-all"
          >
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
            <div className="relative">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                <Tag className="w-6 h-6 text-[#7C4DFF]" />
              </div>
              <h3 className="font-black text-lg text-gray-900 mb-2 group-hover:text-[#7C4DFF] transition-colors">管理标签</h3>
              <p className="text-sm text-gray-600 mb-4 font-medium">添加和编辑文章标签</p>
              <div className="flex items-center gap-2 text-sm font-black text-[#7C4DFF]">
                <span>前往管理</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </div>
            </div>
          </Link>

          <Link
            href="/dashboard/comments"
            className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all"
          >
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
            <div className="relative">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                <MessageSquare className="w-6 h-6 text-[#FF4D94]" />
              </div>
              <h3 className="font-black text-lg text-gray-900 mb-2 group-hover:text-[#FF4D94] transition-colors">管理评论</h3>
              <p className="text-sm text-gray-600 mb-4 font-medium">审核和回复用户评论</p>
              <div className="flex items-center gap-2 text-sm font-black text-[#FF4D94]">
                <span>前往管理</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </div>
            </div>
          </Link>
        </div>
      )}
    </div>
  )
}

// blog-system/layouts/dashboard.vue
<script setup lang="ts">
import {
  Home, LayoutDashboard, FileText, Image, FolderOpen, Tag,
  MessageSquare, MessageCircle, Users, Settings, LogOut, Menu, X
} from 'lucide-vue-next'

const client = useSupabaseClient()
const user = useSupabaseUser()
const route = useRoute()

// 移动端菜单状态
const mobileMenuOpen = ref(false)

// 获取用户信息
const { data: userProfile } = await useAsyncData('user-profile', async () => {
  if (!user.value) return null
  
  const { data } = await client
    .from('profiles')
    .select('*')
    .eq('id', user.value.id)
    .single()
  
  return data
})

// 检查是否是超级管理员
const SUPER_ADMIN_FAMILY_ID = '79ed05a1-e0e5-4d8c-9a79-d8756c488171'
const isSuperAdmin = computed(() => 
  userProfile.value?.role === 'admin' && userProfile.value?.family_id === SUPER_ADMIN_FAMILY_ID
)

const userName = computed(() => 
  userProfile.value?.name || user.value?.email?.split('@')[0] || '用户'
)

const userAvatar = computed(() => userProfile.value?.avatar_url)

const getRoleLabel = () => {
  if (isSuperAdmin.value) return '超级管理员'
  if (userProfile.value?.role === 'admin') return '家长'
  if (userProfile.value?.role === 'editor') return '编辑'
  return '作者'
}

// 导航菜单
const navItems = computed(() => {
  const items = [
    { href: '/dashboard', icon: LayoutDashboard, label: '概览' },
    { href: '/dashboard/posts', icon: FileText, label: '文章' },
    { href: '/dashboard/media', icon: Image, label: '媒体库' },
  ]

  if (isSuperAdmin.value) {
    items.push(
      { href: '/dashboard/categories', icon: FolderOpen, label: '分类' },
      { href: '/dashboard/tags', icon: Tag, label: '标签' },
      { href: '/dashboard/comments', icon: MessageSquare, label: '评论' },
      { href: '/dashboard/users', icon: Users, label: '用户' },
      { href: '/dashboard/settings', icon: Settings, label: '设置' }
    )
  }

  return items
})

// 判断是否激活
const isActive = (href: string) => {
  if (href === '/dashboard') {
    return route.path === '/dashboard'
  }
  return route.path.startsWith(href)
}

// 退出登录
const handleLogout = async () => {
  await client.auth.signOut()
  navigateTo('/auth/unified')
}

// 关闭移动端菜单
watch(() => route.path, () => {
  mobileMenuOpen.value = false
})
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-[#FDFCFD] via-[#FFF5F9] to-[#EAF6FF]">
    <!-- Top Bar - Desktop -->
    <div class="hidden lg:block fixed top-0 right-0 left-72 bg-white/90 backdrop-blur-xl border-b border-gray-100 z-40 shadow-sm">
      <div class="flex items-center justify-between px-6 lg:px-8 py-4">
        <div class="text-sm font-bold text-gray-600">
          欢迎回来，<span class="text-[#FF4D94] font-black">{{ userName + '的家庭' }}</span>
        </div>
        <div class="flex items-center gap-4">
          <div class="flex items-center gap-3 px-4 py-2 rounded-2xl bg-white border border-gray-100 shadow-sm hover:shadow-md transition-all">
            <div v-if="userAvatar" class="w-9 h-9 rounded-xl border-2 border-gray-100 shadow-sm overflow-hidden">
              <img 
                :src="userAvatar" 
                :alt="userName"
                class="w-full h-full object-cover"
              />
            </div>
            <div v-else class="w-9 h-9 rounded-xl bg-gradient-to-br from-[#FF4D94] to-[#7C4DFF] flex items-center justify-center shadow-sm border-2 border-white">
              <span class="text-white text-sm font-black">
                {{ userName.charAt(0).toUpperCase() }}
              </span>
            </div>
            <div class="flex flex-col">
              <div class="text-sm font-black text-gray-900">{{ userName + '的家庭' }}</div>
              <div :class="['text-xs font-bold', isSuperAdmin ? 'text-[#FF4D94]' : 'text-gray-500']">
                {{ getRoleLabel() }}
              </div>
            </div>
          </div>
          <button
            @click="handleLogout"
            class="flex items-center gap-2 px-4 py-2 rounded-2xl bg-white border border-gray-100 hover:border-red-200 hover:bg-red-50 text-gray-700 hover:text-red-600 transition-all text-sm font-bold"
          >
            <LogOut class="w-4 h-4" />
            <span>退出</span>
          </button>
        </div>
      </div>
    </div>

    <div class="flex">
      <!-- Sidebar - Desktop -->
      <aside class="hidden lg:flex lg:flex-col w-72 bg-white/95 backdrop-blur-xl border-r border-gray-100 min-h-screen fixed left-0 top-0 shadow-xl">
        <!-- Logo Section -->
        <div class="p-6 border-b border-gray-100 flex-shrink-0">
          <NuxtLink to="/dashboard" class="flex items-center gap-3 group">
            <div class="relative">
              <div class="absolute inset-0 bg-gradient-to-br from-[#FF4D94] to-[#7C4DFF] rounded-2xl blur-md opacity-30 group-hover:opacity-50 transition-opacity"></div>
              <div class="relative w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94] to-[#7C4DFF] flex items-center justify-center text-white p-2.5 shadow-lg group-hover:scale-105 transition-transform">
                <Logo class="w-full h-full" />
              </div>
            </div>
            <div class="flex flex-col">
              <span class="text-lg font-black bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] bg-clip-text text-transparent tracking-tight">元气银行</span>
              <span class="text-xs text-gray-500 font-bold uppercase tracking-wider">管理后台</span>
            </div>
          </NuxtLink>
        </div>

        <!-- Navigation -->
        <div class="flex-1 overflow-y-auto p-5">
          <nav class="space-y-1.5">
            <NuxtLink
              v-for="item in navItems"
              :key="item.href"
              :to="item.href"
              :class="[
                'group flex items-center gap-3 px-4 py-3 rounded-2xl transition-all text-sm font-bold relative overflow-hidden',
                isActive(item.href)
                  ? 'bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] text-white shadow-lg shadow-[#FF4D94]/20'
                  : 'text-gray-700 hover:bg-gradient-to-r hover:from-[#FF4D94]/5 hover:to-[#7C4DFF]/5 hover:text-[#FF4D94]'
              ]"
            >
              <component
                :is="item.icon"
                :class="[
                  'w-5 h-5 relative z-10 transition-colors',
                  isActive(item.href) ? 'text-white' : 'text-gray-500 group-hover:text-[#FF4D94]'
                ]"
              />
              <span class="relative z-10">{{ item.label }}</span>
              <div v-if="isActive(item.href)" class="absolute right-2 top-1/2 -translate-y-1/2 w-1.5 h-6 bg-white/40 rounded-l-full"></div>
            </NuxtLink>
          </nav>
        </div>

        <!-- Bottom Actions -->
        <div class="p-5 border-t border-gray-100 space-y-2 flex-shrink-0">
          <a 
            href="https://www.familybank.chat/"
            target="_blank"
            rel="noopener noreferrer"
            class="flex items-center gap-3 px-4 py-3 rounded-2xl bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] text-white transition-all text-sm font-black hover:shadow-xl hover:scale-105 active:scale-95"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            <span>家庭积分系统</span>
          </a>
          <NuxtLink 
            to="/" 
            class="flex items-center gap-3 px-4 py-3 rounded-2xl hover:bg-gradient-to-r hover:from-[#FF4D94]/5 hover:to-[#7C4DFF]/5 transition-all text-sm font-bold text-gray-700 hover:text-[#FF4D94] border border-gray-100 hover:border-[#FF4D94]/30"
          >
            <Home class="w-5 h-5" />
            <span>返回首页</span>
          </NuxtLink>
        </div>
      </aside>

      <!-- Mobile Header -->
      <div class="lg:hidden fixed top-0 left-0 right-0 bg-white/95 backdrop-blur-xl border-b border-gray-100 z-50 shadow-sm">
        <div class="flex items-center justify-between px-4 py-3">
          <NuxtLink to="/dashboard" class="flex items-center gap-2">
            <div class="w-9 h-9 rounded-2xl bg-gradient-to-br from-[#FF4D94] to-[#7C4DFF] flex items-center justify-center text-white p-2 shadow-lg">
              <Logo class="w-full h-full" />
            </div>
            <span class="text-base font-black bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] bg-clip-text text-transparent tracking-tight">元气银行</span>
          </NuxtLink>
          <button
            @click="mobileMenuOpen = !mobileMenuOpen"
            class="p-2 rounded-xl hover:bg-gray-100 transition-colors"
          >
            <Menu v-if="!mobileMenuOpen" class="w-6 h-6 text-gray-700" />
            <X v-else class="w-6 h-6 text-gray-700" />
          </button>
        </div>

        <!-- Mobile Menu -->
        <div v-if="mobileMenuOpen" class="border-t border-gray-100 bg-white">
          <nav class="p-4 space-y-1">
            <NuxtLink
              v-for="item in navItems"
              :key="item.href"
              :to="item.href"
              :class="[
                'flex items-center gap-3 px-4 py-3 rounded-2xl transition-all text-sm font-bold',
                isActive(item.href)
                  ? 'bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] text-white'
                  : 'text-gray-700 hover:bg-gray-50'
              ]"
            >
              <component :is="item.icon" class="w-5 h-5" />
              <span>{{ item.label }}</span>
            </NuxtLink>
          </nav>
          <div class="p-4 border-t border-gray-100">
            <button
              @click="handleLogout"
              class="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-2xl bg-red-50 text-red-600 hover:bg-red-100 transition-all text-sm font-bold"
            >
              <LogOut class="w-4 h-4" />
              <span>退出登录</span>
            </button>
          </div>
        </div>
      </div>

      <!-- Main content -->
      <main class="flex-1 lg:ml-72 lg:mt-[73px] p-4 sm:p-6 lg:p-8 pt-20 lg:pt-8">
        <div class="max-w-7xl mx-auto">
          <slot />
        </div>
      </main>
    </div>
  </div>
</template>
