// blog-system-nextjs-backup/src/app/dashboard/page.tsx
import { createClient } from '@/lib/supabase/server'
import { FileText, Eye, MessageSquare, Users, Plus, ArrowRight, FolderOpen, Tag, AlertCircle, Clock } from 'lucide-react'
import Link from 'next/link'
import { formatDate, formatAuthorName } from '@/lib/utils'
import { QuickReviewActions } from '@/components/dashboard/QuickReviewActions'

export default async function DashboardPage() {
  const supabase = await createClient()
  
  const { data: { user } } = await supabase.auth.getUser()
  const { data: profile } = await supabase
    .from('profiles')
    .select('name, role, family_id')
    .eq('id', user?.id)
    .maybeSingle()

  // 检查是否是超管
  const isSuperAdmin = profile?.role === 'admin' && profile?.family_id === '79ed05a1-e0e5-4d8c-9a79-d8756c488171'

  // Get statistics - 根据权限过滤
  // 构建统计查询
  let postsCountQuery = supabase.from('posts').select('*', { count: 'exact', head: true })
  let commentsCountQuery = supabase.from('comments').select('*', { count: 'exact', head: true })
  let viewsQuery = supabase.from('posts').select('view_count')
  
  // 如果不是超管，只统计自己的数据
  if (!isSuperAdmin) {
    postsCountQuery = postsCountQuery.eq('author_id', user?.id)
    viewsQuery = viewsQuery.eq('author_id', user?.id)
    
    // 评论：只统计自己文章的评论
    // 需要通过 posts 表关联
    commentsCountQuery = supabase
      .from('comments')
      .select('*, posts!inner(author_id)', { count: 'exact', head: true })
      .eq('posts.author_id', user?.id)
  }
  
  const [
    { count: totalPosts },
    { count: totalComments },
    { data: totalViews }
  ] = await Promise.all([
    postsCountQuery,
    commentsCountQuery,
    viewsQuery
  ])

  // 用户数统计：只有超管才显示
  let totalUsers = 0
  if (isSuperAdmin) {
    const { count } = await supabase.from('profiles').select('*', { count: 'exact', head: true })
    totalUsers = count || 0
  }

  const viewCount = totalViews?.reduce((sum, post) => sum + (post.view_count || 0), 0) || 0 || 0

  // Get recent posts with author info
  // 非超管只能看到自己的文章
  let recentPostsQuery = supabase
    .from('posts')
    .select(`
      id, 
      title, 
      status, 
      review_status,
      updated_at, 
      view_count,
      profiles!posts_author_id_fkey(name, avatar_url)
    `)
    .order('updated_at', { ascending: false })
    .limit(5)
  
  // 如果不是超管，只显示自己的文章
  if (!isSuperAdmin) {
    recentPostsQuery = recentPostsQuery.eq('author_id', user?.id)
  }
  
  const { data: recentPosts } = await recentPostsQuery

  // Get pending posts (only for super admin)
  let pendingPosts = null
  if (isSuperAdmin) {
    const { data } = await supabase
      .from('posts')
      .select(`
        id, 
        title, 
        status,
        review_status,
        created_at,
        profiles!posts_author_id_fkey(name, avatar_url)
      `)
      .eq('review_status', 'pending')
      .order('created_at', { ascending: false })
      .limit(5)
    pendingPosts = data
  }

  // Get pending comments (only for super admin)
  let pendingComments = null
  if (isSuperAdmin) {
    const { data } = await supabase
      .from('comments')
      .select(`
        id,
        content,
        author_name,
        created_at,
        post_id,
        posts!inner(title, slug)
      `)
      .eq('status', 'pending')
      .order('created_at', { ascending: false })
      .limit(5)
    pendingComments = data
  }

  const stats = {
    totalPosts: totalPosts || 0,
    totalViews: viewCount,
    totalComments: totalComments || 0,
    totalUsers: totalUsers || 0,
  }

  return (
    <div className="space-y-6 sm:space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-black bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] bg-clip-text text-transparent mb-2 tracking-tight">
            欢迎回来，{profile?.name || user?.email?.split('@')[0] || '用户'}
          </h1>
          <p className="text-sm sm:text-base text-gray-600 font-medium">查看数据统计和最新动态</p>
        </div>
        <Link
          href="/dashboard/posts/new"
          className="w-full sm:w-auto flex items-center justify-center gap-2 px-5 sm:px-6 py-2.5 sm:py-3 bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] text-white rounded-2xl font-black hover:shadow-xl hover:scale-105 active:scale-95 transition-all text-sm sm:text-base"
        >
          <Plus className="w-4 h-4 sm:w-5 sm:h-5" />
          <span>新建文章</span>
        </Link>
      </div>

      {/* Stats Grid */}
      <div className={`grid grid-cols-1 sm:grid-cols-2 ${isSuperAdmin ? 'lg:grid-cols-4' : 'lg:grid-cols-3'} gap-4 sm:gap-6`}>
        <div className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all">
          <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
          <div className="relative">
            <div className="flex items-center justify-between mb-4">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                <FileText className="w-6 h-6 text-[#FF4D94]" />
              </div>
              <span className="text-xs font-black text-[#FF4D94] bg-[#FF4D94]/10 px-3 py-1 rounded-full uppercase tracking-wider">文章</span>
            </div>
            <div className="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{stats.totalPosts}</div>
            <div className="text-xs sm:text-sm text-gray-600 font-bold">{isSuperAdmin ? '总文章数' : '我的文章'}</div>
          </div>
        </div>

        <div className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#7C4DFF]/30 transition-all">
          <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
          <div className="relative">
            <div className="flex items-center justify-between mb-4">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                <Eye className="w-6 h-6 text-[#7C4DFF]" />
              </div>
              <span className="text-xs font-black text-[#7C4DFF] bg-[#7C4DFF]/10 px-3 py-1 rounded-full uppercase tracking-wider">浏览</span>
            </div>
            <div className="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{stats.totalViews.toLocaleString()}</div>
            <div className="text-xs sm:text-sm text-gray-600 font-bold">{isSuperAdmin ? '总浏览量' : '我的浏览量'}</div>
          </div>
        </div>

        <div className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all">
          <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
          <div className="relative">
            <div className="flex items-center justify-between mb-4">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                <MessageSquare className="w-6 h-6 text-[#FF4D94]" />
              </div>
              <span className="text-xs font-black text-[#FF4D94] bg-[#FF4D94]/10 px-3 py-1 rounded-full uppercase tracking-wider">评论</span>
            </div>
            <div className="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{stats.totalComments}</div>
            <div className="text-xs sm:text-sm text-gray-600 font-bold">{isSuperAdmin ? '总评论数' : '我的评论数'}</div>
          </div>
        </div>

        {/* 只有超管才显示用户统计 */}
        {isSuperAdmin && (
          <div className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#7C4DFF]/30 transition-all">
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
            <div className="relative">
              <div className="flex items-center justify-between mb-4">
                <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
                  <Users className="w-6 h-6 text-[#7C4DFF]" />
                </div>
                <span className="text-xs font-black text-[#7C4DFF] bg-[#7C4DFF]/10 px-3 py-1 rounded-full uppercase tracking-wider">用户</span>
              </div>
              <div className="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{stats.totalUsers}</div>
              <div className="text-xs sm:text-sm text-gray-600 font-bold">注册用户</div>
            </div>
          </div>
        )}
      </div>

      {/* Recent Posts */}
      <div className="bg-white rounded-3xl border border-gray-100 shadow-lg overflow-hidden">
        <div className="p-5 sm:p-6 border-b border-gray-100 bg-gradient-to-r from-[#FF4D94]/5 to-[#7C4DFF]/5">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div>
              <h2 className="text-xl sm:text-2xl font-black text-gray-900 mb-1">最近文章</h2>
              <p className="text-xs sm:text-sm text-gray-600 font-medium">{isSuperAdmin ? '最近发布的内容' : '您最近发布的内容'}</p>
            </div>
            <Link
              href="/dashboard/posts"
              className="flex items-center gap-2 text-xs sm:text-sm font-black text-[#FF4D94] hover:text-[#7C4DFF] transition-colors"
            >
              查看全部
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
        <div className="divide-y divide-gray-100">
          {recentPosts && recentPosts.length > 0 ? (
            recentPosts.map((post: any) => (
              <div
                key={post.id}
                className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 sm:p-6 hover:bg-gradient-to-r hover:from-[#FF4D94]/5 hover:to-[#7C4DFF]/5 transition-all group"
              >
                <Link
                  href={`/dashboard/posts/${post.id}/edit`}
                  className="flex-1 min-w-0"
                >
                  <h3 className="font-black text-base sm:text-lg text-gray-900 mb-2 group-hover:text-[#FF4D94] transition-colors line-clamp-2">
                    {post.title}
                  </h3>
                  <div className="flex flex-wrap items-center gap-2 sm:gap-4 text-xs sm:text-sm text-gray-600">
                    <span className="font-black text-[#FF4D94]">
                      {formatAuthorName(post.profiles)}
                    </span>
                    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold ${
                      post.status === 'published' 
                        ? 'bg-green-50 text-green-700 border border-green-200' 
                        : 'bg-yellow-50 text-yellow-700 border border-yellow-200'
                    }`}>
                      <span className={`w-1.5 h-1.5 rounded-full ${
                        post.status === 'published' ? 'bg-green-500' : 'bg-yellow-500'
                      }`}></span>
                      {post.status === 'published' ? '已发布' : '草稿'}
                    </span>
                    {post.review_status && (
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold ${
                        post.review_status === 'approved' 
                          ? 'bg-blue-50 text-blue-700 border border-blue-200'
                          : post.review_status === 'pending'
                          ? 'bg-orange-50 text-orange-700 border border-orange-200'
                          : 'bg-red-50 text-red-700 border border-red-200'
                      }`}>
                        {post.review_status === 'approved' ? '已审核' : post.review_status === 'pending' ? '待审核' : '已拒绝'}
                      </span>
                    )}
                    <span className="flex items-center gap-1 font-medium">
                      <Eye className="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                      {post.view_count} 浏览
                    </span>
                    <span className="font-medium">{formatDate(post.updated_at)}</span>
                  </div>
                </Link>
                <div className="flex items-center gap-2 flex-shrink-0">
                  {isSuperAdmin && post.review_status === 'pending' && (
                    <QuickReviewActions
                      type="post"
                      id={post.id}
                    />
                  )}
                  <Link href={`/dashboard/posts/${post.id}/edit`}>
                    <ArrowRight className="w-5 h-5 text-gray-400 group-hover:text-[#FF4D94] group-hover:translate-x-1 transition-all" />
                  </Link>
                </div>
              </div>
            ))
          ) : (
            <div className="p-12 text-center">
              <div className="w-16 h-16 rounded-3xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center mx-auto mb-4">
                <FileText className="w-8 h-8 text-[#FF4D94]" />
              </div>
              <p className="text-gray-600 font-bold">还没有文章，开始创作第一篇吧！</p>
            </div>
          )}
        </div>
      </div>

      {/* Pending Posts (Admin Only) */}
      {isSuperAdmin && pendingPosts && pendingPosts.length > 0 && (
        <div className="bg-white rounded-3xl border border-orange-100 shadow-lg overflow-hidden">
          <div className="p-5 sm:p-6 border-b border-orange-100 bg-gradient-to-r from-orange-50/50 to-yellow-50/50">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-orange-100 to-yellow-100 flex items-center justify-center">
                  <Clock className="w-5 h-5 text-orange-600" />
                </div>
                <div>
                  <h2 className="text-xl sm:text-2xl font-black text-gray-900 mb-1">待审核文章</h2>
                  <p className="text-xs sm:text-sm text-gray-600 font-medium">需要您审核的文章</p>
                </div>
              </div>
              <Link
                href="/dashboard/posts"
                className="flex items-center gap-2 text-xs sm:text-sm font-black text-orange-600 hover:text-orange-700 transition-colors"
              >
                查看全部
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>
          <div className="divide-y divide-gray-100">
            {pendingPosts.map((post: any) => (
              <div
                key={post.id}
                className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 sm:p-6 hover:bg-gradient-to-r hover:from-orange-50/30 hover:to-yellow-50/30 transition-all group"
              >
                <Link href={`/dashboard/posts/${post.id}/review`} className="flex-1 min-w-0">
                  <h3 className="font-black text-base sm:text-lg text-gray-900 mb-2 group-hover:text-orange-600 transition-colors line-clamp-2">
                    {post.title}
                  </h3>
                  <div className="flex flex-wrap items-center gap-2 sm:gap-4 text-xs sm:text-sm text-gray-600">
                    <span className="font-black text-[#FF4D94]">
                      {formatAuthorName(post.profiles)}
                    </span>
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold bg-orange-50 text-orange-700 border border-orange-200">
                      <AlertCircle className="w-3 h-3" />
                      待审核
                    </span>
                    <span className="font-medium">{formatDate(post.created_at)}</span>
                  </div>
                </Link>
                <div className="flex items-center gap-3 flex-shrink-0">
                  <QuickReviewActions type="post" id={post.id} />
                  <Link href={`/dashboard/posts/${post.id}/review`}>
                    <ArrowRight className="w-5 h-5 text-gray-400 group-hover:text-orange-600 transition-all" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Pending Comments (Admin Only) */}
      {isSuperAdmin && pendingComments && pendingComments.length > 0 && (
        <div className="bg-white rounded-3xl border border-blue-100 shadow-lg overflow-hidden">
          <div className="p-5 sm:p-6 border-b border-blue-100 bg-gradient-to-r from-blue-50/50 to-indigo-50/50">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-blue-100 to-indigo-100 flex items-center justify-center">
                  <MessageSquare className="w-5 h-5 text-blue-600" />
                </div>
                <div>
                  <h2 className="text-xl sm:text-2xl font-black text-gray-900 mb-1">待审核评论</h2>
                  <p className="text-xs sm:text-sm text-gray-600 font-medium">需要您审核的评论</p>
                </div>
              </div>
              <Link
                href="/dashboard/comments"
                className="flex items-center gap-2 text-xs sm:text-sm font-black text-blue-600 hover:text-blue-700 transition-colors"
              >
                查看全部
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>
          <div className="divide-y divide-gray-100">
            {pendingComments.map((comment: any) => (
              <div
                key={comment.id}
                className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 sm:p-6 hover:bg-gradient-to-r hover:from-blue-50/30 hover:to-indigo-50/30 transition-all group"
              >
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-2 sm:gap-3 mb-2">
                    <span className="font-black text-gray-900">{comment.author_name}</span>
                    <span className="text-xs sm:text-sm text-gray-500 font-medium">评论了</span>
                    <Link 
                      href={`/blog/${comment.posts?.slug}`}
                      className="text-xs sm:text-sm font-bold text-[#FF4D94] hover:text-[#7C4DFF] truncate max-w-xs transition-colors"
                    >
                      {comment.posts?.title}
                    </Link>
                  </div>
                  <p className="text-xs sm:text-sm text-gray-700 mb-2 line-clamp-2 font-medium">{comment.content}</p>
                  <div className="flex flex-wrap items-center gap-2 sm:gap-4 text-xs sm:text-sm text-gray-600">
                    <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold bg-blue-50 text-blue-700 border border-blue-200">
                      <AlertCircle className="w-3 h-3" />
                      待审核
                    </span>
                    <span className="font-medium">{formatDate(comment.created_at)}</span>
                  </div>
                </div>
                <div className="flex items-center gap-3 flex-shrink-0">
                  <QuickReviewActions type="comment" id={comment.id} />
                  <Link href="/dashboard/comments">
                    <ArrowRight className="w-5 h-5 text-gray-400 group-hover:text-blue-600 transition-all" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Quick Actions - 只有超管才显示 */}
      {isSuperAdmin && (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
          <Link
            href="/dashboard/categories"
            className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all"
          >
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
            <div className="relative">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                <FolderOpen className="w-6 h-6 text-[#FF4D94]" />
              </div>
              <h3 className="font-black text-lg text-gray-900 mb-2 group-hover:text-[#FF4D94] transition-colors">管理分类</h3>
              <p className="text-sm text-gray-600 mb-4 font-medium">组织和管理文章分类</p>
              <div className="flex items-center gap-2 text-sm font-black text-[#FF4D94]">
                <span>前往管理</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </div>
            </div>
          </Link>

          <Link
            href="/dashboard/tags"
            className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#7C4DFF]/30 transition-all"
          >
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
            <div className="relative">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                <Tag className="w-6 h-6 text-[#7C4DFF]" />
              </div>
              <h3 className="font-black text-lg text-gray-900 mb-2 group-hover:text-[#7C4DFF] transition-colors">管理标签</h3>
              <p className="text-sm text-gray-600 mb-4 font-medium">添加和编辑文章标签</p>
              <div className="flex items-center gap-2 text-sm font-black text-[#7C4DFF]">
                <span>前往管理</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </div>
            </div>
          </Link>

          <Link
            href="/dashboard/comments"
            className="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all"
          >
            <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
            <div className="relative">
              <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                <MessageSquare className="w-6 h-6 text-[#FF4D94]" />
              </div>
              <h3 className="font-black text-lg text-gray-900 mb-2 group-hover:text-[#FF4D94] transition-colors">管理评论</h3>
              <p className="text-sm text-gray-600 mb-4 font-medium">审核和回复用户评论</p>
              <div className="flex items-center gap-2 text-sm font-black text-[#FF4D94]">
                <span>前往管理</span>
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </div>
            </div>
          </Link>
        </div>
      )}
    </div>
  )
}

// blog-system/pages/dashboard/index.vue
<script setup lang="ts">
import {
  FileText, Eye, MessageSquare, Users, Plus, ArrowRight,
  FolderOpen, Tag, AlertCircle, Clock
} from 'lucide-vue-next'

definePageMeta({
  middleware: 'auth',
  layout: 'dashboard'
})

const client = useSupabaseClient()
const user = useSupabaseUser()

const formatDate = (dateString: string) => {
  const date = new Date(dateString)
  return date.toLocaleDateString('zh-CN', { year: 'numeric', month: '2-digit', day: '2-digit' })
}

const formatAuthorName = (profile: any) => {
  return profile?.name ? `${profile.name}的家庭` : '匿名家庭'
}

// 获取用户信息和数据
const { data: dashboardData } = await useAsyncData('dashboard-data', async () => {
  if (!user.value) return null

  // 获取用户 profile
  const { data: profile } = await client
    .from('profiles')
    .select('name, role, family_id')
    .eq('id', user.value.id)
    .single()

  // 检查是否是超级管理员
  const SUPER_ADMIN_FAMILY_ID = '79ed05a1-e0e5-4d8c-9a79-d8756c488171'
  const isSuperAdmin = profile?.role === 'admin' && profile?.family_id === SUPER_ADMIN_FAMILY_ID

  // 构建统计查询
  let postsCountQuery = client.from('posts').select('*', { count: 'exact', head: true })
  let commentsCountQuery = client.from('comments').select('*', { count: 'exact', head: true })
  let viewsQuery = client.from('posts').select('view_count')

  // 如果不是超级管理员，只统计自己的数据
  if (!isSuperAdmin) {
    postsCountQuery = postsCountQuery.eq('author_id', user.value.id)
    viewsQuery = viewsQuery.eq('author_id', user.value.id)
  }

  const [
    { count: totalPosts },
    { count: totalComments },
    { data: totalViews }
  ] = await Promise.all([
    postsCountQuery,
    commentsCountQuery,
    viewsQuery
  ])

  // 用户数统计：只有超级管理员才显示
  let totalUsers = 0
  if (isSuperAdmin) {
    const { count } = await client.from('profiles').select('*', { count: 'exact', head: true })
    totalUsers = count || 0
  }

  const viewCount = totalViews?.reduce((sum: number, post: any) => sum + (post.view_count || 0), 0) || 0

  // 获取最近文章
  let recentPostsQuery = client
    .from('posts')
    .select('id, title, status, updated_at, view_count, profiles!posts_author_id_fkey(name, avatar_url)')
    .order('updated_at', { ascending: false })
    .limit(5)

  if (!isSuperAdmin) {
    recentPostsQuery = recentPostsQuery.eq('author_id', user.value.id)
  }

  const { data: recentPosts } = await recentPostsQuery

  // 获取待审核文章（仅超级管理员）
  let pendingPosts = null
  if (isSuperAdmin) {
    const { data } = await client
      .from('posts')
      .select('id, title, status, created_at, profiles!posts_author_id_fkey(name, avatar_url)')
      .eq('status', 'draft')
      .order('created_at', { ascending: false })
      .limit(5)
    pendingPosts = data
  }

  return {
    profile,
    isSuperAdmin,
    stats: {
      totalPosts: totalPosts || 0,
      totalViews: viewCount,
      totalComments: totalComments || 0,
      totalUsers
    },
    recentPosts: recentPosts || [],
    pendingPosts
  }
})

useSeoMeta({
  title: 'Dashboard - 元气银行管理后台'
})
</script>

<template>
  <div v-if="dashboardData" class="space-y-6 sm:space-y-8">
    <!-- Header -->
    <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl sm:text-3xl md:text-4xl font-black bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] bg-clip-text text-transparent mb-2 tracking-tight">
          欢迎回来，{{ dashboardData.profile?.name + '的家庭' || user?.email?.split('@')[0] || '用户' }}
        </h1>
        <p class="text-sm sm:text-base text-gray-600 font-medium">查看数据统计和最新动态</p>
      </div>
      <NuxtLink
        to="/dashboard/posts/new"
        class="w-full sm:w-auto flex items-center justify-center gap-2 px-5 sm:px-6 py-2.5 sm:py-3 bg-gradient-to-r from-[#FF4D94] to-[#7C4DFF] text-white rounded-2xl font-black hover:shadow-xl hover:scale-105 active:scale-95 transition-all text-sm sm:text-base"
      >
        <Plus class="w-4 h-4 sm:w-5 sm:h-5" />
        <span>新建文章</span>
      </NuxtLink>
    </div>

    <!-- Stats Grid -->
    <div :class="['grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6', dashboardData.isSuperAdmin ? 'lg:grid-cols-4' : 'lg:grid-cols-3']">
      <div class="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all">
        <div class="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
        <div class="relative">
          <div class="flex items-center justify-between mb-4">
            <div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
              <FileText class="w-6 h-6 text-[#FF4D94]" />
            </div>
            <span class="text-xs font-black text-[#FF4D94] bg-[#FF4D94]/10 px-3 py-1 rounded-full uppercase tracking-wider">文章</span>
          </div>
          <div class="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{{ dashboardData.stats.totalPosts }}</div>
          <div class="text-xs sm:text-sm text-gray-600 font-bold">{{ dashboardData.isSuperAdmin ? '总文章数' : '我的文章' }}</div>
        </div>
      </div>

      <div class="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#7C4DFF]/30 transition-all">
        <div class="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
        <div class="relative">
          <div class="flex items-center justify-between mb-4">
            <div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
              <Eye class="w-6 h-6 text-[#7C4DFF]" />
            </div>
            <span class="text-xs font-black text-[#7C4DFF] bg-[#7C4DFF]/10 px-3 py-1 rounded-full uppercase tracking-wider">浏览</span>
          </div>
          <div class="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{{ dashboardData.stats.totalViews.toLocaleString() }}</div>
          <div class="text-xs sm:text-sm text-gray-600 font-bold">{{ dashboardData.isSuperAdmin ? '总浏览量' : '我的浏览量' }}</div>
        </div>
      </div>

      <div class="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all">
        <div class="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
        <div class="relative">
          <div class="flex items-center justify-between mb-4">
            <div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
              <MessageSquare class="w-6 h-6 text-[#FF4D94]" />
            </div>
            <span class="text-xs font-black text-[#FF4D94] bg-[#FF4D94]/10 px-3 py-1 rounded-full uppercase tracking-wider">评论</span>
          </div>
          <div class="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{{ dashboardData.stats.totalComments }}</div>
          <div class="text-xs sm:text-sm text-gray-600 font-bold">{{ dashboardData.isSuperAdmin ? '总评论数' : '我的评论数' }}</div>
        </div>
      </div>

      <div v-if="dashboardData.isSuperAdmin" class="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#7C4DFF]/30 transition-all">
        <div class="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
        <div class="relative">
          <div class="flex items-center justify-between mb-4">
            <div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 flex items-center justify-center group-hover:scale-110 transition-transform">
              <Users class="w-6 h-6 text-[#7C4DFF]" />
            </div>
            <span class="text-xs font-black text-[#7C4DFF] bg-[#7C4DFF]/10 px-3 py-1 rounded-full uppercase tracking-wider">用户</span>
          </div>
          <div class="text-3xl sm:text-4xl font-black text-gray-900 mb-1">{{ dashboardData.stats.totalUsers }}</div>
          <div class="text-xs sm:text-sm text-gray-600 font-bold">注册用户</div>
        </div>
      </div>
    </div>

    <!-- Recent Posts -->
    <div class="bg-white rounded-3xl border border-gray-100 shadow-lg overflow-hidden">
      <div class="p-5 sm:p-6 border-b border-gray-100 bg-gradient-to-r from-[#FF4D94]/5 to-[#7C4DFF]/5">
        <div class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div>
            <h2 class="text-xl sm:text-2xl font-black text-gray-900 mb-1">最近文章</h2>
            <p class="text-xs sm:text-sm text-gray-600 font-medium">{{ dashboardData.isSuperAdmin ? '最近发布的内容' : '您最近发布的内容' }}</p>
          </div>
          <NuxtLink
            to="/dashboard/posts"
            class="flex items-center gap-2 text-xs sm:text-sm font-black text-[#FF4D94] hover:text-[#7C4DFF] transition-colors"
          >
            查看全部
            <ArrowRight class="w-4 h-4" />
          </NuxtLink>
        </div>
      </div>
      <div class="divide-y divide-gray-100">
        <div
          v-if="dashboardData.recentPosts.length > 0"
          v-for="post in dashboardData.recentPosts"
          :key="post.id"
          class="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 sm:p-6 hover:bg-gradient-to-r hover:from-[#FF4D94]/5 hover:to-[#7C4DFF]/5 transition-all group"
        >
          <NuxtLink
            :to="`/dashboard/posts/${post.id}/edit`"
            class="flex-1 min-w-0"
          >
            <h3 class="font-black text-base sm:text-lg text-gray-900 mb-2 group-hover:text-[#FF4D94] transition-colors line-clamp-2">
              {{ post.title }}
            </h3>
            <div class="flex flex-wrap items-center gap-2 sm:gap-4 text-xs sm:text-sm text-gray-600">
              <span class="font-black text-[#FF4D94]">
                {{ formatAuthorName(post.profiles) }}
              </span>
              <span :class="[
                'inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-bold',
                post.status === 'published' 
                  ? 'bg-green-50 text-green-700 border border-green-200' 
                  : 'bg-yellow-50 text-yellow-700 border border-yellow-200'
              ]">
                <span :class="['w-1.5 h-1.5 rounded-full', post.status === 'published' ? 'bg-green-500' : 'bg-yellow-500']"></span>
                {{ post.status === 'published' ? '已发布' : '草稿' }}
              </span>
              <span class="flex items-center gap-1 font-medium">
                <Eye class="w-3.5 h-3.5 sm:w-4 sm:h-4" />
                {{ post.view_count }} 浏览
              </span>
              <span class="font-medium">{{ formatDate(post.updated_at) }}</span>
            </div>
          </NuxtLink>
          <NuxtLink :to="`/dashboard/posts/${post.id}/edit`">
            <ArrowRight class="w-5 h-5 text-gray-400 group-hover:text-[#FF4D94] group-hover:translate-x-1 transition-all" />
          </NuxtLink>
        </div>
        <div v-else class="p-12 text-center">
          <div class="w-16 h-16 rounded-3xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center mx-auto mb-4">
            <FileText class="w-8 h-8 text-[#FF4D94]" />
          </div>
          <p class="text-gray-600 font-bold">还没有文章，开始创作第一篇吧！</p>
        </div>
      </div>
    </div>

    <!-- Quick Actions - 只有超级管理员才显示 -->
    <div v-if="dashboardData.isSuperAdmin" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
      <NuxtLink
        to="/dashboard/categories"
        class="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all"
      >
        <div class="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
        <div class="relative">
          <div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
            <FolderOpen class="w-6 h-6 text-[#FF4D94]" />
          </div>
          <h3 class="font-black text-lg text-gray-900 mb-2 group-hover:text-[#FF4D94] transition-colors">管理分类</h3>
          <p class="text-sm text-gray-600 mb-4 font-medium">组织和管理文章分类</p>
          <div class="flex items-center gap-2 text-sm font-black text-[#FF4D94]">
            <span>前往管理</span>
            <ArrowRight class="w-4 h-4 group-hover:translate-x-1 transition-transform" />
          </div>
        </div>
      </NuxtLink>

      <NuxtLink
        to="/dashboard/tags"
        class="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#7C4DFF]/30 transition-all"
      >
        <div class="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
        <div class="relative">
          <div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#7C4DFF]/10 to-[#FF4D94]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
            <Tag class="w-6 h-6 text-[#7C4DFF]" />
          </div>
          <h3 class="font-black text-lg text-gray-900 mb-2 group-hover:text-[#7C4DFF] transition-colors">管理标签</h3>
          <p class="text-sm text-gray-600 mb-4 font-medium">添加和编辑文章标签</p>
          <div class="flex items-center gap-2 text-sm font-black text-[#7C4DFF]">
            <span>前往管理</span>
            <ArrowRight class="w-4 h-4 group-hover:translate-x-1 transition-transform" />
          </div>
        </div>
      </NuxtLink>

      <NuxtLink
        to="/dashboard/comments"
        class="group relative overflow-hidden bg-white rounded-3xl p-5 sm:p-6 border border-gray-100 hover:shadow-2xl hover:border-[#FF4D94]/30 transition-all"
      >
        <div class="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity -translate-y-1/2 translate-x-1/2"></div>
        <div class="relative">
          <div class="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#FF4D94]/10 to-[#7C4DFF]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
            <MessageSquare class="w-6 h-6 text-[#FF4D94]" />
          </div>
          <h3 class="font-black text-lg text-gray-900 mb-2 group-hover:text-[#FF4D94] transition-colors">管理评论</h3>
          <p class="text-sm text-gray-600 mb-4 font-medium">审核和回复用户评论</p>
          <div class="flex items-center gap-2 text-sm font-black text-[#FF4D94]">
            <span>前往管理</span>
            <ArrowRight class="w-4 h-4 group-hover:translate-x-1 transition-transform" />
          </div>
        </div>
      </NuxtLink>
    </div>
  </div>
</template>
